# -*- coding: utf-8 -*-
"""task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIBxHYpTXyVAgNxOKhWRn3M082igACMP

**PROBLEM STATEMENT**

Unemployment is measured by the unemployment rate which is the number of people who are unemployed as a percentage of the total labour force. We have seen a sharp increase in the unemployment rate during Covid-19, so analyzing the unemployment rate can be a good data science projeCT.

**Import the Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly .express as px

"""**Loading the dataset**"""

data = pd.read_csv('/content/Unemployment_Rate_upto_11_2020.csv')
data

data.info()

data.describe()

data.isnull().sum()

data.columns = ['States','Date','Frequency','Estimated Unemployment Rate',
                'Estimated Employed','Estimated Labour Participation Rate',
                'Region','Longitude','Latitude']

data.head()

"""**CHECKING THE CORRELATION BETWEEN THE FEATURE OF DATASET**"""

import seaborn as sns
import matplotlib.pyplot as plt

# Select only the numerical columns for correlation analysis
numerical_data = data.select_dtypes(include=['number'])

plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(8,6))
ax = sns.heatmap(numerical_data.corr(), annot=True,linewidth=3)
ax.tick_params(size=10,color='w',labelsize=10, labelcolor='w')
plt.show()

"""**Estimated no of employee according to different region of india**"""

# plotting histplot

data.columns=['States','Date','Frequency','Estimated Unemployment Rate',
                'Estimated Employed','Estimated Labour Participation Rate',
                'Region','Longitude','Latitude']
plt.title('Indian Unemployment')
sns.histplot(x='Estimated Employed',hue='Region',data=data)
plt.show()

"""**Unemployment rate according to different regions of india**"""

# plotting histplot

plt.figure(figsize=(10,8))
plt.title("Indian Unemployment")
sns.histplot(x="Estimated Unemployment Rate",hue='Region',data=data)
plt.show()

"""**Dashboard to analyze the unemployment rate of each Indian state**"""

# plotting sunburst

unemployment = data[['States','Region','Estimated Unemployment Rate']]
figure = px.sunburst(unemployment,path=['Region','States'],
                     values='Estimated Unemployment Rate',
                     width=700,height=600, color_continuous_scale='RdY1Gn',
                     title="Unemployment Rate in India")
figure.show()